version: '3.9'


services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      # maps port 8000 on our local machine to port 8000 on docker container
      - 8000:8000
    volumes:
    # maps
      - ./app:/app
    # command i.e used to run the service
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"